# application-local-docker.yml
# Use este profile se quiser testar com Oracle local via Docker
# Para usar: mvn spring-boot:run -Dspring-boot.run.profiles=local-docker

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: ${SPRING_DATASOURCE_USERNAME:appuser}
    password: ${SPRING_DATASOURCE_PASSWORD:appsecret}
  
  flyway:
    schemas: ${SPRING_DATASOURCE_USERNAME:APPUSER}
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.esg.energia: DEBUG
