# application-local-docker.yml
# Use este profile se quiser testar com Oracle local via Docker
# Para usar: mvn spring-boot:run -Dspring-boot.run.profiles=local-docker

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: appuser
    password: appsecret
  
  flyway:
    schemas: APPUSER
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.esg.energia: DEBUG
